### ISSUE TITLE
[Feature]  flaky test case collection

### ISSUE THREAD

**Issue by wonderflow** [kubevela/kubevela#1499]
Let's collect all flaky test case here and kill them one by one.

**Comment by wonderflow** [comment]
```
failure [0.406 seconds]
Component Revision Enabled with apply once only force
/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go:509
  revision enabled should create workload with revisionName and work upgrade with new revision successfully [It]
  /home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go:540

  Expected
      <nil>: nil
  to be not found

  /home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go:690
------------------------------
```

**Comment by wonderflow** [comment]
```
• Failure [13.465 seconds]
Test application controller clean up appRevision
/home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_revision_clean_up_test.go:45
  Test clean up rollout appRevision [It]
  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_revision_clean_up_test.go:173

  Expected
      <*errors.StatusError | 0xc0006a2280>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "admission webhook \"validating.core.oam.dev.v1beta1.approllouts\" denied the request: spec.rolloutPlan.rolloutBatches: Required value: the rollout has to have batches",
              Reason: "",
              Details: nil,
              Code: 422,
          },
      }
  to be nil

  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_revision_clean_up_test.go:275
------------------------------
HealthScope 
```

**Comment by captainroy-hy** [comment]
```
--- FAIL: TestMakeHTTPRequest (0.65s)
    rollout_webhook_test.go:125: 
        Test failed case with retry
        r.Reconcile(...): want code `501`, got code:`-1` got err: Post "http://127.0.0.1:1081": http: ContentLength=16 with Body length 0 
FAIL
coverage: 26.1% of statements
FAIL	github.com/oam-dev/kubevela/pkg/controller/common/rollout	0.960s
```

**Comment by zzxwill** [comment]
`license_finder` failed several times though all licensers are approved.

```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/oam-dev/kubevela git:(terraform) license_finder --decisions_file .license/dependency_decisions.yml
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
LicenseFinder::GoModules: is active

All dependencies are approved for use
```

```
Run license_finder --decisions_file .license/dependency_decisions.yml
  license_finder --decisions_file .license/dependency_decisions.yml
  shell: /usr/bin/bash -e {0}
LicenseFinder::GoModules: is active
/opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:61:in `block in packages_info': Command 'GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...' failed to execute (RuntimeError)
GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...: did not succeed.
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:32:in `chdir'
GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...: Getting the dependencies from go list failed 
	go: downloading github.com/crossplane/crossplane-runtime v0.10.0
go: downloading k8s.io/apimachinery v0.18.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading sigs.k8s.io/kind v0.9.0
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/spf13/cobra v1.1.1
go: downloading k8s.io/api v0.18.8
go: downloading k8s.io/client-go v0.18.8
go: downloading github.com/coreos/prometheus-operator v0.41.1
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading k8s.io/kube-openapi v0.0.0-20200410145947-bcb3869e6f29
go: downloading k8s.io/klog/v2 v2.4.0
go: downloading github.com/swaggo/swag v1.6.7
go: downloading sigs.k8s.io/controller-runtime v0.6.2
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading github.com/onsi/gomega v1.10.3
go: downloading github.com/google/gofuzz v1.1.0
go: downloading github.com/AlecAivazis/survey/v2 v2.1.1
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/gin-gonic/gin v1.6.3
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading cuelang.org/go v0.2.2
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading k8s.io/kubectl v0.18.6
go: downloading github.com/go-openapi/spec v0.19.8
go: downloading github.com/googleapis/gnostic v0.4.0
go: downloading github.com/gin-contrib/sse v0.1.0
go: downloading github.com/oam-dev/terraform-controller v0.1.2
go: downloading github.com/openkruise/kruise-api v0.7.0
go: downloading github.com/google/go-github/v32 v32.1.0
go: downloading helm.sh/helm/v3 v3.2.4
go: downloading github.com/hinshun/vt10x v0.0.0-20180616224451-1954e6464174
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/mholt/archiver/v3 v3.3.0
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/json-iterator/go v1.1.10
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/tidwall/gjson v1.6.8
go: downloading github.com/onsi/ginkgo v1.14.1
go: downloading github.com/Azure/go-autorest/autorest/adal v0.8.3
go: downloading google.golang.org/grpc v1.29.1
go: downloading github.com/go-playground/locales v0.13.0
go: downloading cloud.google.com/go v0.56.0
go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
go: downloading github.com/opencontainers/runc v0.1.1
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/pelletier/go-toml v1.8.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: downloading github.com/Azure/go-autorest/tracing v0.5.0
go: downloading google.golang.org/genproto v0.0.0-20200603110839-e855014d5736
go: downloading github.com/docker/docker-credential-helpers v0.6.3
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/containerd/continuity v0.0.0-20200107194136-26c1120b8d41
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/gorilla/mux v1.7.3
go: downloading github.com/docker/go-metrics v0.0.0-20180209012529-399ea8c73916
go: updates to go.sum needed, disabled by -mod=readonly

	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:32:in `packages_info'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:20:in `current_packages'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/scanner.rb:42:in `each'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/scanner.rb:42:in `flat_map'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/scanner.rb:42:in `active_packages'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/core.rb:83:in `current_packages'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/core.rb:78:in `decision_applier'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/forwardable.rb:224:in `any_packages?'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/license_aggregator.rb:15:in `map'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/lib/license_finder/cli/main.rb:112:in `action_items'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/bin/license_finder:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/license_finder:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/license_finder:23:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by captainroy-hy** [comment]
Test application containing kube module
/home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/kube_app_test.go:42
  Test deploy an application containing kube module [It]
  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/kube_app_test.go:156

  Timed out after 60.000s.
  Expected
      <bool>: false
  to be true

  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/kube_app_test.go:200
------------------------------

**Comment by wonderflow** [comment]
```
• Failure [123.121 seconds]
Cloneset based rollout tests
/home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/rollout_plan_test.go:46
  Test revert the rollout plan in the middle of rollout [It]
  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/rollout_plan_test.go:538

  Timed out after 120.000s.
  Expected
      <v1alpha1.RollingState>: rollingInBatches
  to equal
      <v1alpha1.RollingState>: rolloutSucceed

  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/rollout_plan_test.go:181
------------------------------
```

**Comment by ryanzhang-oss** [comment]
it's hard to debug those tests with few clues, is there way to restore the server logs?

**Comment by zzxwill** [comment]
> `license_finder` failed several times though all licensers are approved.
> 
> ```
> ➜  /Users/zhouzhengxi/Programming/golang/src/github.com/oam-dev/kubevela git:(terraform) license_finder --decisions_file .license/dependency_decisions.yml
> Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
> Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
> Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
> 	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
> 	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
> 	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
> 	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
> 	from /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/license_finder-6.12.2/bin/license_finder:6:in `<top (required)>'
> 	from /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/license_finder:23:in `load'
> 	from /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/license_finder:23:in `<main>'
> Error: Process completed with exit code 1.
> ```

This is caused by out-fo-date go.sum. Try to update it in this way.
```
go clean -modcache
go mod tidy
```

**Comment by wonderflow** [comment]
```
• Failure [73.827 seconds]
Test application cross namespace resource
/home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_resourcetracker_test.go:44
  Test update application by delete a cross namespace trait resource [It]
  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_resourcetracker_test.go:319

  Timed out after 60.009s.
  Expected
      <*errors.errorString | 0xc000441e50>: {
          s: "failed generate cross namespace trait",
      }
  to be nil

  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_resourcetracker_test.go:396
------------------------------
Test application cross namespace resource 
  Test application have two different workload
  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_resourcetracker_test.go:436
```

**Comment by zzxwill** [comment]
A compatiblity-test case:

```
•! Panic [0.606 seconds]
Test ApplicationContext Controller
/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller_test.go:38
  Applying ApplicationContext [It]
  /home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller_test.go:41

  Test Panicked
  runtime error: index out of range [0] with length 0
  /opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:88

  Full Stack Trace
  github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext.glob..func1.1.1()
  	/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller_test.go:164 +0x208b
  github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc0001019f0, 0x2a31553, 0x18, 0xc000b5afa8, 0x0, 0x3e63e10, 0x81, 0x2a, 0xc000258400, 0xb59)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/suite/suite.go:147 +0x329
  github.com/onsi/ginkgo.Context(0x2a31553, 0x18, 0xc000b5afa8, 0x0)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/ginkgo_dsl.go:316 +0x103
  github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext.glob..func1.1()
  	/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext/applicationcontext_controller_test.go:42 +0x8b
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000313260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/runner.go:113 +0xf4
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc000313260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/runner.go:64 +0x16b
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc000244580, 0x2d9ef40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/it_node.go:26 +0xa3
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc000224000, 0x0, 0x2d9ef40, 0xc0004e15c0)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/spec/spec.go:215 +0x782
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc000224000, 0x2d9ef40, 0xc0004e15c0)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/spec/spec.go:138 +0x17f
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000162640, 0xc000224000, 0x0)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/specrunner/spec_runner.go:200 +0x173
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000162640, 0x1)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/specrunner/spec_runner.go:170 +0x217
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000162640, 0x8)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/specrunner/spec_runner.go:66 +0x141
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0001019f0, 0x7f13be2279e8, 0xc0001cfe60, 0x2a30f0b, 0x18, 0xc00043b2b0, 0x1, 0x1, 0x2df3d00, 0xc0004e15c0, ...)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/suite/suite.go:62 +0x6a0
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x2da0220, 0xc0001cfe60, 0x2a30f0b, 0x18, 0xc000071e70, 0x1, 0x1, 0xc000071e70)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/ginkgo_dsl.go:219 +0x34a
  github.com/onsi/ginkgo.RunSpecs(0x2da0220, 0xc0001cfe60, 0x2a30f0b, 0x18, 0x0)
  	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/ginkgo_dsl.go:200 +0x24e
  github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext.TestComponentDefinition(0xc0001cfe60)
  	/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/applicationcontext/suit_test.go:53 +0xf9
  testing.tRunner(0xc0001cfe60, 0x2ae7980)
  	/opt/hostedtoolcache/go/1.14.15/x64/src/testing/testing.go:1050 +0x1ec
  created by testing.(*T).Run
  	/opt/hostedtoolcache/go/1.14.15/x64/src/testing/testing.go:1095 +0x538
------------------------------
I0430 09:01:21.213302   35373 render.go:162] "render a component" component name="comp1" component revision="" is generated by application=false is the component rolling=false is the appConfig a rollout template=false
E0430 09:01:21.224204   35373 event.go:269] Unable to write event: 'Post "http://127.0.0.1:39839/api/v1/namespaces/default/events": dial tcp 127.0.0.1:39839: connect: connection refused' (may retry after sleeping)


Summarizing 1 Failure:

[Panic!] Test ApplicationContext Controller [It] Applying ApplicationContext 
/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/panic.go:88

Ran 1 of 1 Specs in 14.042 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped
```

**Comment by captainroy-hy** [comment]
```console
Cloneset based app embed rollout tests 
  Test application only upgrade batchPartition
  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_embed_rollout_test.go:254
STEP: Start to run a test, clean up previous resources
STEP: make sure all the resources are removed
STEP: Install CloneSet based componentDefinition
STEP: Wait for the rollout `app-roll-out-2-v1` to succeed
STEP: Verify AppContext rolling status
STEP: Verify cloneset  status
STEP: Verify  pod status
STEP: upgrade first batch partition, verify the middle state
STEP: Clean up resources after a test
STEP: Delete the entire namespaceName app-rollout-e2e-test-79ae28daa041571d

• Failure [150.146 seconds]
Cloneset based app embed rollout tests
/home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_embed_rollout_test.go:46
  Test application only upgrade batchPartition [It]
  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_embed_rollout_test.go:254

  Timed out after 120.003s.
  Expected
      <*errors.errorString | 0xc000385160>: {
          s: "app status upgraded status error",
      }
  to be nil

  /home/github/actions-runner/_work/kubevela/kubevela/test/e2e-test/app_embed_rollout_test.go:311
------------------------------
```

**Comment by captainroy-hy** [comment]
in compatiblity unit test.
```console
2021-06-24T05:37:48.5244422Z   /home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go:53
2021-06-24T05:37:48.5245650Z [90m------------------------------[0m
2021-06-24T05:37:48.5246820Z [1mSTEP[0m: Stop the controller
2021-06-24T05:37:48.5247593Z [91m[1mPanic [0.001 seconds][0m
2021-06-24T05:37:48.5248490Z [91m[1m[AfterSuite] AfterSuite [0m
2021-06-24T05:37:48.5250327Z [37m/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go:107[0m
2021-06-24T05:37:48.5251469Z 
2021-06-24T05:37:48.5252373Z   [91m[1mTest Panicked[0m
2021-06-24T05:37:48.5253120Z   [91mclose of nil channel[0m
2021-06-24T05:37:48.5255757Z   /opt/hostedtoolcache/go/1.16.5/x64/src/runtime/chan.go:357
2021-06-24T05:37:48.5256134Z 
2021-06-24T05:37:48.5256753Z   [91mFull Stack Trace[0m
2021-06-24T05:37:48.5258214Z   github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition.glob..func3()
2021-06-24T05:37:48.5259915Z   	/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go:109 +0x8f
2021-06-24T05:37:48.5261056Z   github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000018960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-06-24T05:37:48.5262170Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/runner.go:113 +0xfd
2021-06-24T05:37:48.5263285Z   github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc000018960, 0xe0a3d0980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-06-24T05:37:48.5264194Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/runner.go:64 +0x185
2021-06-24T05:37:48.5265519Z   github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run(0xc000462c80, 0x1, 0x1, 0x0, 0x0, 0x7f458aad0008)
2021-06-24T05:37:48.5266890Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/leafnodes/suite_nodes.go:25 +0xba
2021-06-24T05:37:48.5267868Z   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runAfterSuite(0xc0003fa3c0, 0x0)
2021-06-24T05:37:48.5268879Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/specrunner/spec_runner.go:138 +0x173
2021-06-24T05:37:48.5269969Z   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc0003fa3c0, 0x8)
2021-06-24T05:37:48.5270880Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/specrunner/spec_runner.go:71 +0xfd
2021-06-24T05:37:48.5272120Z   github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc00047b090, 0x7f45605a1648, 0xc000338180, 0x2aae2a1, 0x15, 0xc000492010, 0x1, 0x1, 0x2e21118, 0xc0003b08c0, ...)
2021-06-24T05:37:48.5274063Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/internal/suite/suite.go:62 +0x6ba
2021-06-24T05:37:48.5275538Z   github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x2ddda60, 0xc000338180, 0x2aae2a1, 0x15, 0xc00006ee70, 0x1, 0x1, 0x0)
2021-06-24T05:37:48.5276755Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/ginkgo_dsl.go:219 +0x358
2021-06-24T05:37:48.5277916Z   github.com/onsi/ginkgo.RunSpecs(0x2ddda60, 0xc000338180, 0x2aae2a1, 0x15, 0x0)
2021-06-24T05:37:48.5278906Z   	/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.13.0/ginkgo_dsl.go:200 +0x259
2021-06-24T05:37:48.5281246Z   github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition.TestTraitDefinition(0xc000338180)
2021-06-24T05:37:48.5282953Z   	/home/runner/work/kubevela/kubevela/pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go:50 +0x109
2021-06-24T05:37:48.5283866Z   testing.tRunner(0xc000338180, 0x2b642e8)
2021-06-24T05:37:48.5284510Z   	/opt/hostedtoolcache/go/1.16.5/x64/src/testing/testing.go:1193 +0x203
2021-06-24T05:37:48.5285245Z   created by testing.(*T).Run
2021-06-24T05:37:48.5285838Z   	/opt/hostedtoolcache/go/1.16.5/x64/src/testing/testing.go:1238 +0x5d8
2021-06-24T05:37:48.5286604Z [90m------------------------------[0m
2021-06-24T05:37:48.5286879Z 
2021-06-24T05:37:48.5287617Z [1m[91mRan 8 of 0 Specs in 60.004 seconds[0m
2021-06-24T05:37:48.5288866Z [1m[91mFAIL![0m -- [32m[1m0 Passed[0m | [91m[1m8 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m
2021-06-24T05:37:48.5289715Z --- FAIL: TestTraitDefinition (60.00s)
2021-06-24T05:37:48.5290366Z FAIL
2021-06-24T05:37:48.5292517Z FAIL	github.com/oam-dev/kubevela/pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition	60.349s
```
