### ISSUE TITLE
[BUG] vela def apply causes a panic while using for loop at template's root level

### ISSUE THREAD

**Issue by kinsolee** [kubevela/kubevela#2092]
**Describe the bug**

A panic will be raised if using for loop at cue definition for vela def apply. 

**To Reproduce**

Let's say we add a plugins parameter on the basic of the official route definition:
```
template: {
	outputs: route: {
		apiVersion: "standard.oam.dev/v1alpha1"
		kind:       "Route"
        ....
	}

       // Add a for loop here
        for i, f in parameter.plugins {
	        outputs: "plugin\(i)": {
                 ....
	        }
        }

	parameter: {
               ...
                // Add plugins parameter
		plugins: {
			....
		}
	}
}
```
Run command `vela def apply vela-templates/definitions/registry/route.cue`:
```
panic: unimplemented type *ast.Comprehension

goroutine 1 [running]:
cuelang.org/go/cue/format.(*formatter).exprRaw(0x140019217d8, 0x1033d90b8, 0x14001b98bc0, 0x0, 0x1)
        /Users/kinso/go/pkg/mod/cuelang.org/go@v0.2.2/cue/format/node.go:692 +0x1798
cuelang.org/go/cue/format.(*formatter).expr1(0x140019217d8, 0x1033d90b8, 0x14001b98bc0, 0x0, 0x1)
        /Users/kinso/go/pkg/mod/cuelang.org/go@v0.2.2/cue/format/node.go:527 +0xd4
cuelang.org/go/cue/format.(*formatter).expr(...)
        /Users/kinso/go/pkg/mod/cuelang.org/go@v0.2.2/cue/format/node.go:518
cuelang.org/go/cue/format.printNode(0x1031314c0, 0x14001b98bc0, 0x14001544aa0, 0x0, 0x20)
        /Users/kinso/go/pkg/mod/cuelang.org/go@v0.2.2/cue/format/node.go:46 +0x1b0
cuelang.org/go/cue/format.(*config).fprint(0x14001986a20, 0x1031314c0, 0x14001b98bc0, 0x14001986a20, 0x103022120, 0x1031314c0, 0x140001bcb00, 0x1033cc888)
        /Users/kinso/go/pkg/mod/cuelang.org/go@v0.2.2/cue/format/format.go:141 +0x8c
cuelang.org/go/cue/format.Node(0x1033cc888, 0x14001b98bc0, 0x140019219f8, 0x1, 0x1, 0x1028f1dc0, 0x1, 0x140001bcb00, 0x160, 0x0)
        /Users/kinso/go/pkg/mod/cuelang.org/go@v0.2.2/cue/format/format.go:87 +0x5c
github.com/oam-dev/kubevela/references/common.encodeDeclsToString(0x14001a303c0, 0x3, 0x3, 0x14001c06000, 0x1a0, 0x0, 0x0)
        /Users/kinso/code/github/oam-dev/kubevela/references/common/definition.go:281 +0xcc
github.com/oam-dev/kubevela/references/common.(*Definition).FromCUEString(0x140001a8c98, 0x14001458d80, 0x44f, 0x14000622d80, 0x44f, 0x0)
        /Users/kinso/code/github/oam-dev/kubevela/references/common/definition.go:338 +0x220
github.com/oam-dev/kubevela/references/cli.NewDefinitionApplyCommand.func1(0x1400016d900, 0x14001611a10, 0x1, 0x1, 0x0, 0x0)
        /Users/kinso/code/github/oam-dev/kubevela/references/cli/def.go:621 +0x184
github.com/spf13/cobra.(*Command).execute(0x1400016d900, 0x140016119f0, 0x1, 0x1, 0x1400016d900, 0x140016119f0)
        /Users/kinso/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x140008f5400, 0x169babfb5b0e1d98, 0x10521d180, 0x1028f1d88)
        /Users/kinso/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/kinso/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /Users/kinso/code/github/oam-dev/kubevela/references/cmd/cli/main.go:34 +0xe4

```

**Expected behavior**

I think we should support this scenario as it's useful when defining multiple similar outputs.

**Screenshots**

**KubeVela Version**

```
Version: master
GitRevision: git-83efbf3e
GolangVersion: go1.16.4

```

**Cluster information**

**Additional context**

**Comment by Somefive** [comment]
I suggest using an alternative for loop as follows
```cue
template: {
        outputs: {
                 // Add a for loop here
                 for i, f in parameter.plugins {
	              "plugin\(i)": {}
                 }
	}
	parameter: {
               ...
                // Add plugins parameter
		plugins: {
			....
		}
	}
}
```
This style is supported in current version of `vela def`. The proposed writing, although should be valid in cue format, is not well supported currently. We will fix this issue as soon as possible.

**Comment by wonderflow** [comment]
@Somefive  what's this issue now?

**Comment by Somefive** [comment]
> @Somefive what's this issue now?

Waiting for CUE to upgrade. This is a bug in CUE 0.2.2. Upgrading to 0.4.0 should will fix it.

**Comment by wonderflow** [comment]
Closing as the master branch has been upgraded to the CUE 0.4 https://github.com/kubevela/kubevela/pull/4425
