### ISSUE TITLE
[BUG] 使用Application 创建 MySQL Operator 出现vela secret 过大的错误

### ISSUE THREAD

**Issue by 0x0034** [kubevela/kubevela#4752]
## 问题描述

使用如下的Yaml 创建Mysql Operator Application .

> mysql 的Helm charts 都是官方仓库的Charts , 链接<https://github.com/mysql/mysql-operator>

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mysql
  namespace: lcc-optimizer
spec:
  components:
    - name: mysql-operator
      type: helm
      properties:
        repoType: "helm"
        url: "http://xxxx"
        chart: "mysql-operator"
        version: "2.0.6"
    - name: mysql-innodbcluster
      type: helm
      dependsOn:
        - mysql-operator
      properties:
        repoType: helm
        url: "http://xxxx"
        chart: "mysql-innodbcluster"
        version: "2.0.6"
        values:
          serverInstances: 1
          routerInstances: 1
          tls:
            useSelfSigned: true
          credentials:
            root:
              user: root
              password: xxxxx
              host: "%"
```

## 报错信息

```
[2022-09-19 05:26:53,510] kopf.objects         [INFO    ] Creation is processed: 1 succeeded; 0 failed.
[2022-09-19 05:26:53,512] kopf.objects         [INFO    ] Handler 'on_secret_create' succeeded.
[2022-09-19 05:26:53,512] kopf.objects         [INFO    ] Creation is processed: 1 succeeded; 0 failed.
[2022-09-19 05:26:53,519] kopf.objects         [INFO    ] Handler 'on_secret_create' succeeded.
[2022-09-19 05:26:53,520] kopf.objects         [INFO    ] Creation is processed: 1 succeeded; 0 failed.
[2022-09-19 05:26:54,402] kopf.objects         [ERROR   ] Throttling for 1 seconds due to an unexpected error: APIClientError('Secret "sh.helm.release.v1.kubevela.v1" is invalid: metadata.annotations: Too long: must have at most 262144 bytes', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'Secret "sh.helm.release.v1.kubevela.v1" is invalid: metadata.annotations: Too long: must have at most 262144 bytes', 'reason': 'Invalid', 'details': {'name': 'sh.helm.release.v1.kubevela.v1', 'kind': 'Secret', 'causes': [{'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}, {'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}, {'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}, {'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}]}, 'code': 422})
Traceback (most recent call last):
  File "/usr/lib/mysqlsh/python-packages/kopf/_cogs/clients/errors.py", line 148, in check_response
    response.raise_for_status()
  File "/usr/lib/mysqlsh/python-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 422, message='Unprocessable Entity', url=URL('https://10.0.128.1:443/api/v1/namespaces/vela-system/secrets/sh.helm.release.v1.kubevela.v1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/mysqlsh/python-packages/kopf/_core/actions/throttlers.py", line 44, in throttled
    yield should_run
  File "/usr/lib/mysqlsh/python-packages/kopf/_core/reactor/processing.py", line 130, in process_resource_event
    applied = await application.apply(
  File "/usr/lib/mysqlsh/python-packages/kopf/_core/actions/application.py", line 60, in apply
    await patch_and_check(
  File "/usr/lib/mysqlsh/python-packages/kopf/_core/actions/application.py", line 131, in patch_and_check
    resulting_body = await patching.patch_obj(
  File "/usr/lib/mysqlsh/python-packages/kopf/_cogs/clients/patching.py", line 47, in patch_obj
    patched_body = await api.patch(
  File "/usr/lib/mysqlsh/python-packages/kopf/_cogs/clients/api.py", line 155, in patch
    response = await request(
  File "/usr/lib/mysqlsh/python-packages/kopf/_cogs/clients/auth.py", line 45, in wrapper
    return await fn(*args, **kwargs, context=context)
  File "/usr/lib/mysqlsh/python-packages/kopf/_cogs/clients/api.py", line 85, in request
    await errors.check_response(response)  # but do not parse it!
  File "/usr/lib/mysqlsh/python-packages/kopf/_cogs/clients/errors.py", line 150, in check_response
    raise cls(payload, status=response.status) from e
kopf._cogs.clients.errors.APIClientError: ('Secret "sh.helm.release.v1.kubevela.v1" is invalid: metadata.annotations: Too long: must have at most 262144 bytes', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'Secret "sh.helm.release.v1.kubevela.v1" is invalid: metadata.annotations: Too long: must have at most 262144 bytes', 'reason': 'Invalid', 'details': {'name': 'sh.helm.release.v1.kubevela.v1', 'kind': 'Secret', 'causes': [{'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}, {'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}, {'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}, {'reason': 'FieldValueTooLong', 'message': 'Too long: must have at most 262144 bytes', 'field': 'metadata.annotations'}]}, 'code': 422})
[2022-09-19 05:26:55,407] kopf.objects         [INFO    ] Throttling is over. Switching back to normal operations.
[2022-09-19 05:35:58,541] kopf.objects         [INFO    ] Handler 'on_secret_create' succeeded.
[2022-09-19 05:35:58,541] kopf.objects         [INFO    ] Creation is processed: 1 succeeded; 0 failed.
[2022-09-19 05:35:58,543] kopf.objects         [INFO    ] Handler 'on_secret_create' succeeded.
```

**Comment by wangyikewxgm** [comment]
这个 app 创建之后，当前的运行状态是什么？

**Comment by 0x0034** [comment]
@wangyikewxgm fluxcd 显示已经安装完成, 但是 其实innodbcluster 是写入crd 再由 operator 创建具体资源

**Comment by wangyikewxgm** [comment]
> @wangyikewxgm fluxcd 显示已经安装完成, 但是 其实innodbcluster 是写入crd 再由 operator 创建具体资源

这个 CRD 对象是什么状态呢？有报错信息吗？

**Comment by 0x0034** [comment]
@wangyikewxgm 

## vela Application 状态

```
/tmp took 5s
➜ vela ls -n lcc-optimizer
APP       	COMPONENT          	TYPE	TRAITS	PHASE  	HEALTHY	STATUS                                                      	CREATED-TIME
clickhouse	clickhouse         	helm	      	running	healthy	Fetch repository successfully, Create helm release          	2022-09-16 14:44:51 +0800 CST
          	                   	    	      	       	       	successfully
lcc-core  	lcc-core           	helm	      	running	healthy	Fetch repository successfully, Create helm release          	2022-09-16 14:32:57 +0800 CST
          	                   	    	      	       	       	successfully
mysql     	mysql-operator     	helm	      	running	healthy	Fetch repository successfully, Create helm release          	2022-09-19 15:33:04 +0800 CST
          	                   	    	      	       	       	successfully
└─      	mysql-innodbcluster	helm	      	running	healthy	Fetch repository successfully, Create helm release          	2022-09-19 15:33:04 +0800 CST
          	                   	    	      	       	       	successfully
```

## CRD innodbclusters 状态

```
/tmp
➜ kubectl get innodbclusters.mysql.oracle.com -A
NAMESPACE       NAME                  STATUS    ONLINE   INSTANCES   ROUTERS   AGE
lcc-optimizer   mysql-innodbcluster   PENDING   0        1           1         41s

/tmp took 5s
➜ kubectl describe  innodbclusters.mysql.oracle.com mysql-innodbcluster -n lcc-optimizer
Name:         mysql-innodbcluster
Namespace:    lcc-optimizer
Labels:       app.kubernetes.io/managed-by=Helm
              helm.toolkit.fluxcd.io/name=mysql-innodbcluster
              helm.toolkit.fluxcd.io/namespace=lcc-optimizer
Annotations:  kopf.zalando.org/last-handled-configuration:
                {"spec":{"baseServerId":1000,"datadirVolumeClaimTemplate":{"accessModes":["[ReadWriteOnce]"],"resources":{"requests":{"storage":"10Gi"}},"...
              meta.helm.sh/release-name: mysql-innodbcluster
              meta.helm.sh/release-namespace: lcc-optimizer
              mysql.oracle.com/mysql-operator-version: 8.0.30-2.0.6
API Version:  mysql.oracle.com/v2
Kind:         InnoDBCluster
Metadata:
  Creation Timestamp:  2022-09-19T07:34:50Z
  Finalizers:
    kopf.zalando.org/KopfFinalizerMarker
  Generation:  1
  Managed Fields:
    API Version:  mysql.oracle.com/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:mysql.oracle.com/mysql-operator-version:
      f:status:
        .:
        f:cluster:
    Manager:      OpenAPI-Generator
    Operation:    Update
    Time:         2022-09-19T07:34:50Z
    API Version:  mysql.oracle.com/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
          f:helm.toolkit.fluxcd.io/name:
          f:helm.toolkit.fluxcd.io/namespace:
      f:spec:
        .:
        f:baseServerId:
        f:datadirVolumeClaimTemplate:
          .:
          f:accessModes:
          f:resources:
          f:storageClassName:
        f:imagePullPolicy:
        f:instances:
        f:router:
          .:
          f:instances:
        f:secretName:
        f:serviceAccountName:
        f:tlsUseSelfSigned:
        f:version:
    Manager:      helm-controller
    Operation:    Update
    Time:         2022-09-19T07:34:50Z
    API Version:  mysql.oracle.com/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kopf.zalando.org/last-handled-configuration:
        f:finalizers:
          .:
          v:"kopf.zalando.org/KopfFinalizerMarker":
      f:status:
        f:kopf:
    Manager:         kopf
    Operation:       Update
    Time:            2022-09-19T07:34:51Z
  Resource Version:  75556388
  UID:               968b7c60-530a-4a0a-833b-b9d340f31d26
Spec:
  Base Server Id:  1000
  Datadir Volume Claim Template:
    Access Modes:
      [ReadWriteOnce]
    Resources:
      Requests:
        Storage:         10Gi
    Storage Class Name:  dice-local-volume
  Image Pull Policy:     IfNotPresent
  Instances:             1
  Router:
    Instances:           1
  Secret Name:           mysql-innodbcluster-cluster-secret
  Service Account Name:  mysql-innodbcluster-sa
  Tls Use Self Signed:   true
  Version:               8.0.30
Status:
  Cluster:
    Last Probe Time:   2022-09-19T07:34:50Z
    Online Instances:  0
    Status:            PENDING
  Kopf:
    Progress:
Events:
  Type    Reason            Age   From      Message
  ----    ------            ----  ----      -------
  Normal  ResourcesCreated  62s   operator  Dependency resources created, switching status to PENDING
  Normal  Logging           63s   kopf      Router Image:              mysql/mysql-router:8.0.30 / IfNotPresent
  Normal  Logging           63s   kopf      Backup profiles:           0
  Normal  Logging           63s   kopf      Router instances:          1
  Normal  Logging           63s   kopf      Server.TLS.useSelfSigned:  True
  Normal  Logging           62s   kopf      Handler 'on_innodbcluster_create' succeeded.
  Normal  Logging           63s   kopf      Backup schedules:  0
  Normal  Logging           63s   kopf      InnoDB Cluster lcc-optimizer/mysql-innodbcluster Edition(Edition.community) Edition
  Normal  Logging           63s   kopf      Sidecar Image:  mysql/mysql-operator:8.0.30-2.0.6 / IfNotPresent
  Normal  Logging           63s   kopf      Base ServerId:  1000
  Normal  Logging           62s   kopf      Handler 'on_innodbcluster_field_instances/spec.instances' succeeded.
  Normal  Logging           63s   kopf      ImageRepository:  mysql
  Normal  Logging           63s   kopf      Initializing InnoDB Cluster name=mysql-innodbcluster namespace=lcc-optimizer
  Normal  Logging           63s   kopf      Server Image:     mysql/mysql-server:8.0.30 / IfNotPresent
  Normal  Logging           63s   kopf      ImagePullPolicy:  ImagePullPolicy.IfNotPresent
  Normal  Logging           62s   kopf      Handler 'on_innodbcluster_field_tls_use_self_signed/spec.tlsUseSelfSigned' succeeded.
  Normal  Logging           62s   kopf      on_innodbcluster_field_tls_use_self_signed
  Normal  Logging           62s   kopf      Handler 'on_innodbcluster_field_image_pull_policy/spec.imagePullPolicy' succeeded.
  Normal  Logging           62s   kopf      Handler 'on_innodbcluster_field_version/spec.version' succeeded.
  Normal  Logging           62s   kopf      Handler 'on_innodbcluster_field_router_instances/spec.router.instances' succeeded.
  Normal  Logging           62s   kopf      Creation is processed: 6 succeeded; 0 failed.
```
CRD因为有依赖资源没有创建成功 , 所以pendiing了, 日志就是上面 报错

**Comment by briankane** [comment]
This issue has been inactive for over 2 years and is scheduled for closure as part of our backlog maintenance.

  **If this issue is still relevant:**
  - Please comment below to keep it open
  - Provide updated context if the original description is outdated

  **Timeline:** If there's no activity by **Friday, October 24th**, this issue will be automatically closed.

  **Note:** Issues can always be reopened if they become relevant again. We encourage the community to reopen and reprioritize any incorrectly 
  closed issues.

**Comment by briankane** [comment]
This issue has been closed following the stale issue notice. 

If this issue is still relevant and should remain open, please:
1. Reopen the issue
2. Remove the 'stale' label
3. Provide an update on the current status or importance

Thank you for your understanding and contribution to KubeVela!
