### ISSUE TITLE
failed to detach OCM cluster 

### ISSUE THREAD

**Issue by maxmiles39** [kubevela/kubevela#5039]
**Describe the bug**
throw errors when to detach the ocm cluster. 

**To Reproduce**
1.  join cluster.  Follow link: https://kubevela.io/docs/platform-engineers/system-operation/working-with-ocm
2. run `vela cluster detach ocm-cluster -p managed-cluster.kubeconfig`
**Expected behavior**
Detach cluster ocm-cluster successfully.

**Screenshots**
F1110 02:20:13.901842    1434 clean.go:45] AppliedManifestWork exist on the managed cluster,
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:860 +0x89
k8s.io/klog/v2.(*loggingT).output(0x51809a0, 0x3, 0x0, 0xc00086c310, 0x1, {0x3f92dc2?, 0x7f80bf95b5b8?}, 0x10?, 0x0)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:825 +0x685
k8s.io/klog/v2.(*loggingT).printDepth(0x51809a0, 0x86c0e0?, 0x0, {0x0, 0x0}, 0x0?, {0xc0012ca890?, 0x1, 0x1})
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:608 +0x1d3
k8s.io/klog/v2.(*loggingT).print(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:590
k8s.io/klog/v2.Fatal(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:1490
github.com/oam-dev/cluster-register/pkg/spoke.CleanSpokeClusterEnv(0x0?)
        /home/runner/go/pkg/mod/github.com/oam-dev/cluster-register@v1.0.4-0.20220928064144-5f76a9d7ca8c/pkg/spoke/clean.go:45 +0xa5
github.com/oam-dev/kubevela/pkg/multicluster.DetachCluster({0x36c53d8, 0xc0000540b8}, {0x36d9a10?, 0xc0001712d0}, {0x7ffc55611f2a, 0x7}, {0xc000541d18, 0x1, 0x18b0005?})
        /home/runner/work/kubevela/kubevela/pkg/multicluster/cluster_management.go:480 +0x295
github.com/oam-dev/kubevela/references/cli.NewClusterDetachCommand.func1(0xc00086e280?, {0xc000aa2b10?, 0x1?, 0x3?})
        /home/runner/work/kubevela/kubevela/references/cli/cluster.go:243 +0x10f
github.com/spf13/cobra.(*Command).execute(0xc00086e280, {0xc000aa2ae0, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000aff900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/runner/work/kubevela/kubevela/references/cmd/cli/main.go:41 +0x18c

goroutine 33 [sleep]:
time.Sleep(0x6fc23ac00)

**KubeVela Version**

CLI Version: v1.6.1
Core Version: 1.6.1
GitRevision: git-f0e3304
GolangVersion: go1.19.2

**Cluster information**
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8-gke.1900", GitCommit:"79209257257c051b27df67c567755783eda93353", GitTreeState:"clean", BuildDate:"2022-07-15T09:23:51Z", GoVersion:"go1.17.11b7", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by Somefive** [comment]
We temporarily do not fully support the detach of OCM clusters due to the underlying complexities. The OCM mode needs to create a network channel between managed cluster and hub cluster. We will work on that in the future. Thanks for the reporting!

**Comment by dwctua** [comment]
thanks @Somefive , will the ocm cli delete still work? any downside?

**Comment by Somefive** [comment]
OCM CLI deletion is not guaranteed by KubeVela Team to work but I think there should be no conflict for using OCM CLI here.

**Comment by USER0308** [comment]
Hi, @maxmiles39  @Somefive Here are some tips which may help you.
There are two command-line tools for detaching managedCluster from hub cluster: vela and clusteradm.
The implemetion of them are the same, checking if any AppliedManifestWork exists in managedCluster first, deleting the klusterlet crd, klusterlet clusterRole, klusterlet rolebinding, klusterlet deployment in open-cluster-management namespace, klusterlet serviceAccount in open-cluster-management namespace, open-cluster-management-agent and open-cluster-management namespace, cluster-bootstrap serviceaccount in open-cluster-management namespace, system:open-cluster-management:bootstrap clusterrole and cluster-bootstrap-sa clusterrolebinding.

So, please check the info about remaining AppliedManifestWork in managed cluster by running this command in managed cluster:
`kubectl get AppliedManifestWork`

If some of them are created by you on purpose of application dispatching, please delete them in hub cluster(yes, you cannot delete them in managed cluster, since it will not work and will be recreated)
`kubectl get manifestwork -n <your-managed-cluster-name>`
`kubectl delete manifestwork -n <your-managed-cluster-name>`

And some of these manifestwork are created by ocm addon(such as cluster-gateway, cluster-proxy,managed-serviceaccount), they will be created by controller even tough deleted in hub cluster.

So, you should follow these steps to delete the addon manifestwork

Firstly, remove the managedCluster from the hub.
`kubectl delete managedCluster <your-managedCluster-name>`

Secondly, delete the managedClusterAddon in managedCluster's namespace
`kubectl get managedClusterAddon -n <your-managedCluster-name> `
`kubectl delete managedClusterAddon -n <your-managedCluster-name> <addon-name>`

Check the info about remaining AppliedManifestWorks in managed cluster again to ensure it is empty.

After cleaning manifestworks and appliedmanifestworks, finally, detach the managedCluster from hub cluster by vela or from managed cluster by clusteradm
In hub cluster: `vela cluster detach <your-managedCluster-name> -p <your-managedCluster-kubeconfig-path>`

or in managed cluster: `clusteradm unjoin -cluster-name=<your-managedCluster-name>`

**Comment by briankane** [comment]
This issue has been inactive for over 2 years and is scheduled for closure as part of our backlog maintenance.

  **If this issue is still relevant:**
  - Please comment below to keep it open
  - Provide updated context if the original description is outdated

  **Timeline:** If there's no activity by **Friday, October 24th**, this issue will be automatically closed.

  **Note:** Issues can always be reopened if they become relevant again. We encourage the community to reopen and reprioritize any incorrectly 
  closed issues.

**Comment by briankane** [comment]
This issue has been closed following the stale issue notice. 

If this issue is still relevant and should remain open, please:
1. Reopen the issue
2. Remove the 'stale' label
3. Provide an update on the current status or importance

Thank you for your understanding and contribution to KubeVela!
