### ISSUE TITLE
Rollout example in document cause crash

### ISSUE THREAD

**Issue by chivalryq** [kubevela/kubevela#5061]
**Describe the bug**

It looks like there is a bug. I am using vela 1.6.1. I am following the steps from https://kubevela.io/docs/end-user/traits/rollout
```shell
vela workflow resume canary-demo -n default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x33dd2a9]
goroutine 1 [running]:
[github.com/oam-dev/kubevela/references/cli.(*WorkflowArgs).generateWorkflowInstance(0xc000281c30](http://github.com/oam-dev/kubevela/references/cli.(*WorkflowArgs).generateWorkflowInstance(0xc000281c30), {0x42c33d8?, 0xc00018c008?}, {0x42d7a90, 0xc000e50bd0})
	[github.com/oam-dev/kubevela/references/cli/workflow.go:279](http://github.com/oam-dev/kubevela/references/cli/workflow.go:279) +0x109
[github.com/oam-dev/kubevela/references/cli.(*WorkflowArgs).getWorkflowInstance(0xc000281c30](http://github.com/oam-dev/kubevela/references/cli.(*WorkflowArgs).getWorkflowInstance(0xc000281c30), {0x42c33d8, 0xc00018c008}, 0x24b345a?, {0xc000f0a930?, 0xc000cb1d28?, 0x1173111?})
	[github.com/oam-dev/kubevela/references/cli/workflow.go:264](http://github.com/oam-dev/kubevela/references/cli/workflow.go:264) +0x55e
[github.com/oam-dev/kubevela/references/cli.(*WorkflowArgs).checkWorkflowNotComplete.func1(0xc0004ef400](http://github.com/oam-dev/kubevela/references/cli.(*WorkflowArgs).checkWorkflowNotComplete.func1(0xc0004ef400), {0xc000f0a930?, 0x1, 0x3?})
	[github.com/oam-dev/kubevela/references/cli/workflow.go:439](http://github.com/oam-dev/kubevela/references/cli/workflow.go:439) +0x65
[github.com/spf13/cobra.(*Command).execute(0xc0004ef400](http://github.com/spf13/cobra.(*Command).execute(0xc0004ef400), {0xc000f0a900, 0x3, 0x3})
	[github.com/spf13/cobra@v1.4.0/command.go:849](http://github.com/spf13/cobra@v1.4.0/command.go:849) +0x5e3
[github.com/spf13/cobra.(*Command).ExecuteC(0xc000a7f400)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc000a7f400))
	[github.com/spf13/cobra@v1.4.0/command.go:974](http://github.com/spf13/cobra@v1.4.0/command.go:974) +0x3bd
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	[github.com/spf13/cobra@v1.4.0/command.go:902](http://github.com/spf13/cobra@v1.4.0/command.go:902)
main.main()
	[github.com/oam-dev/kubevela/references/cmd/cli/main.go:41](http://github.com/oam-dev/kubevela/references/cmd/cli/main.go:41) +0x18c
```

**Original post in slack**: https://cloud-native.slack.com/archives/C01BLQ3HTJA/p1668118758256389?thread_ts=1667843516.987959&cid=C01BLQ3HTJA

**To Reproduce**

https://kubevela.io/docs/end-user/traits/rollout

**Expected behavior**

example works

**Screenshots**

**KubeVela Version**

1.6.1

**Cluster information**

**Additional context**

**Comment by FogDong** [comment]
Fixed in #5037
