### ISSUE TITLE
[BUG] CUE format panic when execute `make reviewable`

### ISSUE THREAD

**Issue by Hanmengnan** [kubevela/kubevela#5948]
**Describe the bug**

When I tried to execute the `make reviewable` command locally, the program crashed. Based on the prompt, I found that this may be related to the format of CUE. I tried upgrading my CUE version but it didn't work. I also tried uninstalling Vela and reinstalling it, but it still didn't work. My environment information and error message are shown below:

```shell
root@Yoga:/home/siegelion/go/src/kubevela# make reviewable 
go generate ./pkg/... ./apis/...
# TODO(yangsoon): kustomize will merge all CRD into a whole file, it may not work if we want patch more than one CRD in this way
/home/siegelion/go/src/kubevela/bin/kustomize build config/crd -o config/crd/base/core.oam.dev_applications.yaml
./hack/crd/cleanup.sh
/home/siegelion/go/src/kubevela/hack/crd /home/siegelion/go/src/kubevela
clean up unused fields of CRDs
/home/siegelion/go/src/kubevela
go run ./hack/crd/dispatch/dispatch.go config/crd/base charts/vela-core/crds
2023/04/30 17:06:46 complete crd files dispatch
rm -f config/crd/base/*
./vela-templates/gen_definitions.sh
[./vela-templates/gen_definitions.sh] Got vela command binary, version information:
CLI Version: master
Core Version: 1.8.0
GitRevision: git-8395fe56
GolangVersion: go1.19.1
[./vela-templates/gen_definitions.sh] Start generating definitions at ./vela-templates ...
[./vela-templates/gen_definitions.sh] (0/3) Generating internal definitions from definitions/internal to ../charts/vela-core/templates/defwithtemplate ... panic: unimplemented type *ast.Comprehension

goroutine 1 [running]:
cuelang.org/go/cue/format.(*formatter).exprRaw(0xc0009f36d0?, {0x36da9e0?, 0xc000ac39c0?}, 0xc0009f3628?, 0x1?)
        /home/siegelion/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/format/node.go:674 +0xa99
cuelang.org/go/cue/format.(*formatter).expr1(0x299e020?, {0x36da9e0?, 0xc000ac39c0}, 0x203000?, 0xc000d8cb40?)
        /home/siegelion/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/format/node.go:523 +0x79
cuelang.org/go/cue/format.(*formatter).expr(...)
        /home/siegelion/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/format/node.go:514
cuelang.org/go/cue/format.printNode({0x2e0a200?, 0xc000ac39c0?}, 0xc000d8cb40)
        /home/siegelion/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/format/node.go:45 +0x1d6
cuelang.org/go/cue/format.(*config).fprint(0xc000f358a0, {0x2e0a200, 0xc000ac39c0})
        /home/siegelion/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/format/format.go:145 +0xcd
cuelang.org/go/cue/format.Node({0x36d2730?, 0xc000ac39c0}, {0xc0009f38a0, 0x1, 0x452a54?})
        /home/siegelion/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/format/format.go:92 +0x98
github.com/oam-dev/kubevela/pkg/definition.encodeDeclsToString({0xc000ab9ec0?, 0x3, 0x0?})
        /home/siegelion/go/src/kubevela/pkg/definition/definition.go:332 +0xd3
github.com/oam-dev/kubevela/pkg/definition.(*Definition).FromCUEString(0xc000f19b30?, {0xc000d5cd80, 0x45b}, 0xc000e386c0)
        /home/siegelion/go/src/kubevela/pkg/definition/definition.go:394 +0x32d
github.com/oam-dev/kubevela/references/cli.NewDefinitionRenderCommand.func1.1({0xc000f19b30, 0x2c}, {0xc0006fc6c0, 0x39})
        /home/siegelion/go/src/kubevela/references/cli/def.go:773 +0x191
github.com/oam-dev/kubevela/references/cli.NewDefinitionRenderCommand.func1(0xc000e8f900, {0xc000c04ff0?, 0x1, 0x5})
        /home/siegelion/go/src/kubevela/references/cli/def.go:833 +0x522
github.com/spf13/cobra.(*Command).execute(0xc000e8f900, {0xc000c04fa0, 0x5, 0x5})
        /home/siegelion/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f3bb80)
        /home/siegelion/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/siegelion/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/siegelion/go/src/kubevela/references/cmd/cli/main.go:41 +0x18c
make: *** [Makefile:118: manifests] Error 2
root@Yoga:/home/siegelion/go/src/kubevela# 
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

```shell 
CLI Version: master
Core Version: 1.8.0
GitRevision: git-8395fe56
GolangVersion: go1.19.1
CUE version: v0.5.0

```

**Cluster information**

**Additional context**

**Comment by Somefive** [comment]
Did you make some edits to you CLI? BTW, the CLI you are using for "make reviewable" is "master", so reinstalling vela will not work. You can run `make vela-cli` to recompile it.

**Comment by Somefive** [comment]
Yes, it looks like a bug related to CUE formating.

**Comment by chivalryq** [comment]
My environment:
```
$ vela version
CLI Version: 1.8.1
Core Version: 1.8.0
GitRevision: git-e528902b
GolangVersion: go1.19.8
```

It works well. Can you try this again? @Hanmengnan 
<img width="1799" alt="image" src="https://github.com/kubevela/kubevela/assets/47812250/f89bba90-eae1-4846-a9b4-5ff0bf97de75">

**Comment by Hanmengnan** [comment]
> My environment:
> 
> ```
> $ vela version
> CLI Version: 1.8.1
> Core Version: 1.8.0
> GitRevision: git-e528902b
> GolangVersion: go1.19.8
> ```
> 
> It works well. Can you try this again? @Hanmengnan <img alt="image" width="1799" src="https://user-images.githubusercontent.com/47812250/237863118-f89bba90-eae1-4846-a9b4-5ff0bf97de75.png">

OK, I will try it again.

**Comment by Hanmengnan** [comment]
> Did you make some edits to you CLI? BTW, the CLI you are using for "make reviewable" is "master", so reinstalling vela will not work. You can run `make vela-cli` to recompile it.

It works, thanks! I will close this issue.
